/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mercadotrueque;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 * Clase JFrame de ventana de buscar, esta genera un solicitudBusqueda
 *
 * @author Gonzalo Astorga
 * @author Alonso Robledo
 * @since mercadotrueque 0.1
 */
public class JFBuscar extends javax.swing.JFrame implements IBusquedaParametro , IVentanaEstatica{

    private String categoriaSeleccion;
    private int regionSeleccion;
    private boolean salir;
    private SolicitudBusqueda solicitudBusqueda;

    public JFBuscar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionOrden = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        botonAtras = new javax.swing.JLabel();
        panelCategoria = new javax.swing.JPanel();
        botonComputacion = new javax.swing.JLabel();
        botonModa = new javax.swing.JLabel();
        botonVehiculo = new javax.swing.JLabel();
        botonHogar = new javax.swing.JLabel();
        botonArte = new javax.swing.JLabel();
        panelRegiones = new javax.swing.JPanel();
        botonTodasLasRegiones = new javax.swing.JLabel();
        botonAricaParinacota = new javax.swing.JLabel();
        botonTarapaca = new javax.swing.JLabel();
        botonAntofagasta = new javax.swing.JLabel();
        botonAtacama = new javax.swing.JLabel();
        botonCoquimbo = new javax.swing.JLabel();
        botonValparaiso = new javax.swing.JLabel();
        botonSantiago = new javax.swing.JLabel();
        botonLBO = new javax.swing.JLabel();
        botonMaule = new javax.swing.JLabel();
        botonNuble = new javax.swing.JLabel();
        botonBioBio = new javax.swing.JLabel();
        botonAraucania = new javax.swing.JLabel();
        botonLosRios = new javax.swing.JLabel();
        botonLosLagos = new javax.swing.JLabel();
        botonCIC = new javax.swing.JLabel();
        botonMagallanes = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textoRegion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textoCategoria = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnaelOrden = new javax.swing.JPanel();
        opcionSinOrden = new javax.swing.JRadioButton();
        opcionAscendente = new javax.swing.JRadioButton();
        opcionDescendente = new javax.swing.JRadioButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Buscar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonAtras.setText("atras");
        botonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(botonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panelCategoria.setBackground(new java.awt.Color(204, 250, 146));
        panelCategoria.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 90, 40));

        botonComputacion.setBackground(new java.awt.Color(255, 208, 198));
        botonComputacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonComputacion.setText("Computacion");
        botonComputacion.setOpaque(true);
        botonComputacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonComputacionMouseClicked(evt);
            }
        });
        panelCategoria.add(botonComputacion);

        botonModa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonModa.setText("Moda");
        botonModa.setOpaque(true);
        botonModa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonModaMouseClicked(evt);
            }
        });
        panelCategoria.add(botonModa);

        botonVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonVehiculo.setText("Vehiculo");
        botonVehiculo.setOpaque(true);
        botonVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVehiculoMouseClicked(evt);
            }
        });
        panelCategoria.add(botonVehiculo);

        botonHogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonHogar.setText("Hogar");
        botonHogar.setOpaque(true);
        botonHogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonHogarMouseClicked(evt);
            }
        });
        panelCategoria.add(botonHogar);

        botonArte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonArte.setText("Arte");
        botonArte.setOpaque(true);
        botonArte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonArteMouseClicked(evt);
            }
        });
        panelCategoria.add(botonArte);

        getContentPane().add(panelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 1250, 130));

        panelRegiones.setBackground(new java.awt.Color(255, 155, 189));
        panelRegiones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 30));

        botonTodasLasRegiones.setBackground(new java.awt.Color(255, 255, 255));
        botonTodasLasRegiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonTodasLasRegiones.setText("Todas las regiones");
        botonTodasLasRegiones.setOpaque(true);
        botonTodasLasRegiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonTodasLasRegionesMouseClicked(evt);
            }
        });
        panelRegiones.add(botonTodasLasRegiones);

        botonAricaParinacota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonAricaParinacota.setText("Arica y Parinacota");
        botonAricaParinacota.setOpaque(true);
        botonAricaParinacota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAricaParinacotaMouseClicked(evt);
            }
        });
        panelRegiones.add(botonAricaParinacota);

        botonTarapaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonTarapaca.setText("Tarapacá");
        botonTarapaca.setOpaque(true);
        botonTarapaca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonTarapacaMouseClicked(evt);
            }
        });
        panelRegiones.add(botonTarapaca);

        botonAntofagasta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonAntofagasta.setText("Antofagasta");
        botonAntofagasta.setOpaque(true);
        botonAntofagasta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAntofagastaMouseClicked(evt);
            }
        });
        panelRegiones.add(botonAntofagasta);

        botonAtacama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonAtacama.setText("Atacama");
        botonAtacama.setOpaque(true);
        botonAtacama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAtacamaMouseClicked(evt);
            }
        });
        panelRegiones.add(botonAtacama);

        botonCoquimbo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonCoquimbo.setText("Coquimbo");
        botonCoquimbo.setOpaque(true);
        botonCoquimbo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCoquimboMouseClicked(evt);
            }
        });
        panelRegiones.add(botonCoquimbo);

        botonValparaiso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonValparaiso.setText("Valparaíso");
        botonValparaiso.setOpaque(true);
        botonValparaiso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonValparaisoMouseClicked(evt);
            }
        });
        panelRegiones.add(botonValparaiso);

        botonSantiago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonSantiago.setText("Metropolitana de Santiago");
        botonSantiago.setOpaque(true);
        botonSantiago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSantiagoMouseClicked(evt);
            }
        });
        panelRegiones.add(botonSantiago);

        botonLBO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonLBO.setText("Libertador Gral.Bernardo O´Higgins");
        botonLBO.setOpaque(true);
        botonLBO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLBOMouseClicked(evt);
            }
        });
        panelRegiones.add(botonLBO);

        botonMaule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonMaule.setText("Maule");
        botonMaule.setOpaque(true);
        botonMaule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMauleMouseClicked(evt);
            }
        });
        panelRegiones.add(botonMaule);

        botonNuble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonNuble.setText("Ñuble");
        botonNuble.setOpaque(true);
        botonNuble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNubleMouseClicked(evt);
            }
        });
        panelRegiones.add(botonNuble);

        botonBioBio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonBioBio.setText("Biobío");
        botonBioBio.setOpaque(true);
        botonBioBio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBioBioMouseClicked(evt);
            }
        });
        panelRegiones.add(botonBioBio);

        botonAraucania.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonAraucania.setText("La Araucanía");
        botonAraucania.setOpaque(true);
        botonAraucania.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAraucaniaMouseClicked(evt);
            }
        });
        panelRegiones.add(botonAraucania);

        botonLosRios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonLosRios.setText("Los Ríos");
        botonLosRios.setOpaque(true);
        botonLosRios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLosRiosMouseClicked(evt);
            }
        });
        panelRegiones.add(botonLosRios);

        botonLosLagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonLosLagos.setText("Los Lagos");
        botonLosLagos.setOpaque(true);
        botonLosLagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLosLagosMouseClicked(evt);
            }
        });
        panelRegiones.add(botonLosLagos);

        botonCIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonCIC.setText("Aysen del Gral. Carlos Ibañez del Campo");
        botonCIC.setOpaque(true);
        botonCIC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCICMouseClicked(evt);
            }
        });
        panelRegiones.add(botonCIC);

        botonMagallanes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonMagallanes.setText("Magallanes y la Antártica Chilena");
        botonMagallanes.setOpaque(true);
        botonMagallanes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMagallanesMouseClicked(evt);
            }
        });
        panelRegiones.add(botonMagallanes);

        getContentPane().add(panelRegiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1250, 260));

        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mercadotrueque/imgDefault.png"))); // NOI18N
        botonBuscar.setText("Buscar!");
        botonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBuscarMouseClicked(evt);
            }
        });
        getContentPane().add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 640, -1, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Region");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Categoria");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, -1));

        textoRegion.setText("jLabel2");
        getContentPane().add(textoRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 630, 350, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jLabel2.setText("Region Seleccionada : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jLabel5.setText("Categoria Seleccionada:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, -1, -1));

        textoCategoria.setText("jLabel6");
        getContentPane().add(textoCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 670, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Ordenar por AlonsoCoin");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, -1, -1));

        pnaelOrden.setBackground(new java.awt.Color(153, 187, 228));
        pnaelOrden.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 13));

        opcionSinOrden.setBackground(new java.awt.Color(33, 123, 117));
        opcionOrden.add(opcionSinOrden);
        opcionSinOrden.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        opcionSinOrden.setForeground(new java.awt.Color(255, 255, 255));
        opcionSinOrden.setText("    Sin orden    ");
        pnaelOrden.add(opcionSinOrden);

        opcionAscendente.setBackground(new java.awt.Color(33, 123, 117));
        opcionOrden.add(opcionAscendente);
        opcionAscendente.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        opcionAscendente.setForeground(new java.awt.Color(255, 255, 255));
        opcionAscendente.setText("  Ascendente  ");
        pnaelOrden.add(opcionAscendente);

        opcionDescendente.setBackground(new java.awt.Color(33, 123, 117));
        opcionOrden.add(opcionDescendente);
        opcionDescendente.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        opcionDescendente.setForeground(new java.awt.Color(255, 255, 255));
        opcionDescendente.setText("Descendente  ");
        pnaelOrden.add(opcionDescendente);

        getContentPane().add(pnaelOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1250, 50));
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     /**
     * Accion de click en boton atras, esto devuelve a Menu
     *
     * @since mercadotrueque 0.1
     */
    private void botonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasMouseClicked
        solicitudBusqueda = null;
        salir = true;
    }//GEN-LAST:event_botonAtrasMouseClicked
    /**
     * Accion click en buscar, obtiene os criterios de busqueda y genera
     * SolicitudBusqueda
     *
     * @since mercadotrueque 0.1
     */
    private void botonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarMouseClicked
        // comprobar seleccion de region
        if (regionSeleccion == -1) {
            JOptionPane.showMessageDialog(null, "Region no Seleccionada");
        }
        // obtenemos categoria
        if (categoriaSeleccion == null) {
            JOptionPane.showMessageDialog(null, "Categoria no Seleccionada");
        }
        //verificamos si se seleccionaron
        if (categoriaSeleccion != null && regionSeleccion != -1) {
            //obtenemos la opcion de orden de busqueda
            int opcionBusqueda;
            if (opcionSinOrden.isSelected()) {
                opcionBusqueda = SIN_ORDEN;
            } else if (opcionAscendente.isSelected()) {
                opcionBusqueda = ASCENDENTE;
            } else {
                opcionBusqueda = DESCENDENTE;
            }
            // crear solicitud //
            SolicitudBusqueda solicitudNueva = new SolicitudBusqueda(regionSeleccion, categoriaSeleccion, opcionBusqueda);
            // asignar a atributo//
            solicitudBusqueda = solicitudNueva;
            salir = true;
        }
    }//GEN-LAST:event_botonBuscarMouseClicked
    /**
     * Accion click region 0 (todas las regiones), queda selecciona esa opcion
     * de region
     *
     * @since mercadotrueque 0.2
     */
    private void botonTodasLasRegionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTodasLasRegionesMouseClicked
        regionSeleccion = 0;
        textoRegion.setText("Todas las regiones");
        refrescarColorRegiones();
        botonTodasLasRegiones.setBackground(new Color(255,204,153));
        textoRegion.updateUI();
    }//GEN-LAST:event_botonTodasLasRegionesMouseClicked
    /**
     * Accion click region 1 (Region de Arica y Parinacota), queda selecciona
     * esa opcion de region
     *
     * @since mercadotrueque 0.2
     */
    private void botonAricaParinacotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAricaParinacotaMouseClicked
        regionSeleccion = 1;
        textoRegion.setText("Region de Arica y Parinacota");
        refrescarColorRegiones();
        botonAricaParinacota.setBackground(new Color(255,204,153));
        textoRegion.updateUI();
    }//GEN-LAST:event_botonAricaParinacotaMouseClicked
    /**
     * Accion click region 2 (Region de Tarapacá), queda selecciona esa opcion
     * de region
     *
     * @since mercadotrueque 0.2
     */
    private void botonTarapacaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTarapacaMouseClicked
        regionSeleccion = 2;
        textoRegion.setText("Region de Tarapacá");
        refrescarColorRegiones();
        botonTarapaca.setBackground(new Color(255,204,153)); 
        botonTarapaca.updateUI();
    }//GEN-LAST:event_botonTarapacaMouseClicked
    /**
     * Accion click region 3 (Region de Antofagasta), queda selecciona esa
     * opcion de region
     *
     * @since mercadotrueque 0.2
     */
    private void botonAntofagastaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAntofagastaMouseClicked
        regionSeleccion = 3;
        textoRegion.setText("Region de Antofagasta");
        refrescarColorRegiones();
        botonAntofagasta.setBackground(new Color(255,204,153));
        textoRegion.updateUI();
    }//GEN-LAST:event_botonAntofagastaMouseClicked
    /**
     * Accion click region 4 (Region de Atacama), queda selecciona esa opcion de
     * region
     *
     * @since mercadotrueque 0.2
     */
    private void botonAtacamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtacamaMouseClicked
        regionSeleccion = 4;
        textoRegion.setText("Region de Atacama");
        refrescarColorRegiones();
        botonAtacama.setBackground(new Color(255,204,153));
        textoRegion.updateUI();
    }//GEN-LAST:event_botonAtacamaMouseClicked
    /**
     * Accion click region 5 (Region de Coquimbo), queda selecciona esa opcion
     * de region
     *
     * @since mercadotrueque 0.2
     */
    private void botonCoquimboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCoquimboMouseClicked
        regionSeleccion = 5;
        textoRegion.setText("Region de Coquimbo");
        refrescarColorRegiones();
        botonCoquimbo.setBackground(new Color(255,204,153));
        textoRegion.updateUI();
    }//GEN-LAST:event_botonCoquimboMouseClicked
    /**
     * Accion click region 6 (Region de Valparaíso), queda selecciona esa opcion
     * de region
     *
     * @since mercadotrueque 0.2
     */
    private void botonValparaisoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonValparaisoMouseClicked
        regionSeleccion = 6;
        textoRegion.setText("Region de Valparaíso");
        refrescarColorRegiones();
        botonValparaiso.setBackground(new Color(255,204,153));
        textoRegion.updateUI();
    }//GEN-LAST:event_botonValparaisoMouseClicked
    /**
     * Accion click region 7 (Region Metropolitana de Santiago), queda
     * selecciona esa opcion de region
     *
     * @since mercadotrueque 0.2
     */
    private void botonSantiagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSantiagoMouseClicked
        regionSeleccion = 7;
        textoRegion.setText("Region Metropolitana de Santiago");
        refrescarColorRegiones();
        botonSantiago.setBackground(new Color(255,204,153));
        textoRegion.updateUI();
    }//GEN-LAST:event_botonSantiagoMouseClicked
    /**
     * Accion click region 8 (Region Metropolitana de Santiago), queda
     * selecciona esa opcion de region
     *
     * @since mercadotrueque 0.2
     */
    private void botonLBOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLBOMouseClicked
        regionSeleccion = 8;
        textoRegion.setText("Region de Libertador Gral.Bernardo O´Higgins");
        refrescarColorRegiones();
        botonLBO.setBackground(new Color(255,204,153));
        textoRegion.updateUI();
    }//GEN-LAST:event_botonLBOMouseClicked
    /**
     * Accion click region 9 (Region de Maule), queda selecciona esa opcion de
     * region
     *
     * @since mercadotrueque 0.2
     */
    private void botonMauleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMauleMouseClicked
        regionSeleccion = 9;
        textoRegion.setText("Region de Maule");
        refrescarColorRegiones();
        botonMaule.setBackground(new Color(255,204,153));
        textoRegion.updateUI();
    }//GEN-LAST:event_botonMauleMouseClicked
    /**
     * Accion click region 10 (Region de Ñuble), queda selecciona esa opcion de
     * region
     *
     * @since mercadotrueque 0.2
     */
    private void botonNubleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNubleMouseClicked
        regionSeleccion = 10;
        textoRegion.setText("Region de Ñuble");
        refrescarColorRegiones();
        botonNuble.setBackground(new Color(255,204,153));
        textoRegion.updateUI();
    }//GEN-LAST:event_botonNubleMouseClicked
    /**
     * Accion click region 11 (Region de Biobío), queda selecciona esa opcion de
     * region
     *
     * @since mercadotrueque 0.2
     */
    private void botonBioBioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBioBioMouseClicked
        regionSeleccion = 11;
        textoRegion.setText("Region de Biobío");
        refrescarColorRegiones();
        botonBioBio.setBackground(new Color(255,204,153));
        textoRegion.updateUI();
    }//GEN-LAST:event_botonBioBioMouseClicked
    /**
     * Accion click region 12 (Region de La Araucanía), queda selecciona esa
     * opcion de region
     *
     * @since mercadotrueque 0.2
     */
    private void botonAraucaniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAraucaniaMouseClicked
        regionSeleccion = 12;
        textoRegion.setText("Region de La Araucanía");
        refrescarColorRegiones();
        botonAraucania.setBackground(new Color(255,204,153));
        textoRegion.updateUI();
    }//GEN-LAST:event_botonAraucaniaMouseClicked
    /**
     * Accion click region 13 (Region de Los Ríosa), queda selecciona esa opcion
     * de region
     *
     * @since mercadotrueque 0.2
     */
    private void botonLosRiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLosRiosMouseClicked
        regionSeleccion = 13;
        textoRegion.setText("Region de Los Ríos");
        refrescarColorRegiones();
        botonLosRios.setBackground(new Color(255,204,153));
        textoRegion.updateUI();
    }//GEN-LAST:event_botonLosRiosMouseClicked
    /**
     * Accion click region 14 (Region de Los Lagos), queda selecciona esa opcion
     * de region
     *
     * @since mercadotrueque 0.2
     */
    private void botonLosLagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLosLagosMouseClicked
        regionSeleccion = 14;
        textoRegion.setText("Region de Los Lagos");
        refrescarColorRegiones();
        botonLosLagos.setBackground(new Color(255,204,153));
        textoRegion.updateUI();
    }//GEN-LAST:event_botonLosLagosMouseClicked
    /**
     * Accion click region 15 (Region Aysen del Gral. Carlos Ibañez del Campo),
     * queda selecciona esa opcion de region
     *
     * @since mercadotrueque 0.2
     */
    private void botonCICMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCICMouseClicked
        regionSeleccion = 15;
        textoRegion.setText("Region Aysen del Gral. Carlos Ibañez del Campo");
        refrescarColorRegiones();
        botonCIC.setBackground(new Color(255,204,153));
        textoRegion.updateUI();
    }//GEN-LAST:event_botonCICMouseClicked
    /**
     * Accion click region 16 (Region de Magallanes y la Antártica Chilena),
     * queda selecciona esa opcion de region
     *
     * @since mercadotrueque 0.2
     */
    private void botonMagallanesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMagallanesMouseClicked
        regionSeleccion = 16;
        textoRegion.setText("Region de Magallanes y la Antártica Chilena");
        refrescarColorRegiones();
        botonMagallanes.setBackground(new Color(255,204,153));
        textoRegion.updateUI();
    }//GEN-LAST:event_botonMagallanesMouseClicked
    /**
     * Accion click categoria Computacion, queda esta opcion como categoria
     * seleccionada
     *
     * @since mercadotrueque 0.2
     */
    private void botonComputacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComputacionMouseClicked
        categoriaSeleccion = "Computacion";
        textoCategoria.setText("Computación");
        refrescarCategoria();
        botonComputacion.setBackground(new Color(255,208,198));
        textoCategoria.updateUI();
    }//GEN-LAST:event_botonComputacionMouseClicked
    /**
     * Accion click categoria Moda, queda esta opcion como categoria
     * seleccionada
     *
     * @since mercadotrueque 0.2
     */
    private void botonModaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonModaMouseClicked
        categoriaSeleccion = "Moda";
        textoCategoria.setText("Moda");
        refrescarCategoria();
        botonModa.setBackground(new Color(255,208,198));
        textoCategoria.updateUI();
    }//GEN-LAST:event_botonModaMouseClicked
    /**
     * Accion click categoria Vehiculo, queda esta opcion como categoria
     * seleccionada
     *
     * @since mercadotrueque 0.2
     */
    private void botonVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVehiculoMouseClicked
        categoriaSeleccion = "Vehiculo";
        textoCategoria.setText("Vehiculo");
        refrescarCategoria();
        botonVehiculo.setBackground(new Color(255,208,198));
        textoCategoria.updateUI();
    }//GEN-LAST:event_botonVehiculoMouseClicked
    /**
     * Accion click categoria Hogar, queda esta opcion como categoria
     * seleccionada
     *
     * @since mercadotrueque 0.2
     */
    private void botonHogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonHogarMouseClicked
        categoriaSeleccion = "Hogar";
        textoCategoria.setText("Hogar");
        refrescarCategoria();
        botonHogar.setBackground(new Color(255,208,198));
        textoCategoria.updateUI();
    }//GEN-LAST:event_botonHogarMouseClicked
    /**
     * Accion click categoria Arte, queda esta opcion como categoria
     * seleccionada
     *
     * @since mercadotrueque 0.2
     */
    private void botonArteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonArteMouseClicked
        categoriaSeleccion = "Arte";
        textoCategoria.setText("Arte");
        refrescarCategoria();
        botonArte.setBackground(new Color(255,208,198));
        textoCategoria.updateUI();
    }//GEN-LAST:event_botonArteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFBuscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel botonAntofagasta;
    private javax.swing.JLabel botonAraucania;
    private javax.swing.JLabel botonAricaParinacota;
    private javax.swing.JLabel botonArte;
    private javax.swing.JLabel botonAtacama;
    private javax.swing.JLabel botonAtras;
    private javax.swing.JLabel botonBioBio;
    private javax.swing.JLabel botonBuscar;
    private javax.swing.JLabel botonCIC;
    private javax.swing.JLabel botonComputacion;
    private javax.swing.JLabel botonCoquimbo;
    private javax.swing.JLabel botonHogar;
    private javax.swing.JLabel botonLBO;
    private javax.swing.JLabel botonLosLagos;
    private javax.swing.JLabel botonLosRios;
    private javax.swing.JLabel botonMagallanes;
    private javax.swing.JLabel botonMaule;
    private javax.swing.JLabel botonModa;
    private javax.swing.JLabel botonNuble;
    private javax.swing.JLabel botonSantiago;
    private javax.swing.JLabel botonTarapaca;
    private javax.swing.JLabel botonTodasLasRegiones;
    private javax.swing.JLabel botonValparaiso;
    private javax.swing.JLabel botonVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton opcionAscendente;
    private javax.swing.JRadioButton opcionDescendente;
    private javax.swing.ButtonGroup opcionOrden;
    private javax.swing.JRadioButton opcionSinOrden;
    private javax.swing.JPanel panelCategoria;
    private javax.swing.JPanel panelRegiones;
    private javax.swing.JPanel pnaelOrden;
    private javax.swing.JLabel textoCategoria;
    private javax.swing.JLabel textoRegion;
    // End of variables declaration//GEN-END:variables
   /**
     * Inicializa posicion y visual de ventana, ademas inicia valores de los
     * atributos
     *
     * @since mercadotrueque 0.2
     */
    public void start() {
        if (!this.isVisible()) {
            this.setLocationRelativeTo(null);
        }
        this.setVisible(true);
        salir = false;
        textoRegion.setText(" - Ninguna seleccionada - ");
        textoCategoria.setText(" - Ninguna seleccionada - ");
        categoriaSeleccion = null;
        regionSeleccion = -1;
        solicitudBusqueda = null;
        opcionSinOrden.setSelected(true);
        refrescarCategoria();
        refrescarColorRegiones();
    }

    /**
     * Retorna si esta listo para salir
     *
     * @return si esta listo para salir
     * @since mercadotrueque 0.1
     */
    public boolean isSalir() {
        return salir;
    }

    /**
     * Retorna solicitud de busqueda
     *
     * @return SolicitudBusqueda creada
     * @since mercadotrueque 0.2
     */
    public SolicitudBusqueda getSolicitud() {
        return solicitudBusqueda;
    }

    /**
     * Cierra ventana
     *
     * @since mercadotrueque 0.1
     */
    public void cerrarVentana() {
        this.dispose();
    }

    private void refrescarColorRegiones() {
        for(int i=0;i<panelRegiones.getComponentCount();i++){
            panelRegiones.getComponent(i).setBackground(Color.white);
        }
    }

    private void refrescarCategoria() {
        for(int i=0;i<panelCategoria.getComponentCount();i++){
            panelCategoria.getComponent(i).setBackground(new Color(204,250,146));
        }
    }
}
